### ISSUE TITLE
Should we disable the dependabot PRs?

### ISSUE THREAD

**Issue by markcellus** [markcellus/cookie-store#111]
@keithamus I noticed we've closed the dep upgrades for dependabot? Do we want to just disable them for the repo? I can do that really quickly if they're becoming annoying. Sorry about that.

**Comment by keithamus** [comment]
Worth keeping IMO, but up to you. I closed them out just because we're going to be iterating on this a lot and it seemed like too much thrashing to update deps which we might remove or reorganise throughout subsequent PRs.

**Comment by markcellus** [comment]
cool, no biggie. I'll open a PR to disable via the config file.
