### ISSUE TITLE
This is not a polyfill

### ISSUE THREAD

**Issue by just-boris** [markcellus/cookie-store#135]
By definition, "polyfill" provides functionality that is *already standardized*, but does not exist in some browsers.

CookieStore API is not a standard yet, so the code cannot be called "polyfill".  The [W3C document](https://www.w3.org/2001/tag/doc/polyfills/#don-t-squat-on-proposed-names-in-speculative-polyfills) calls them "speculative polyfills" and they also suggest to not define the global object for not yet standard features to avoid conflicts with the future standard spec.

**Comment by karlhorky** [comment]
I guess the correct term for the interim could be "prollyfill"?

**Comment by just-boris** [comment]
"Prollyfill" looks very similar to "polyfill", some people could assume it is just a typo. If the goal here is to show potential users more clear information about the state of the project, it would be better to use longer but also less ambiguous terms.

**Comment by karlhorky** [comment]
Ah, I was just referring that this is the existing term that the industry uses for this purpose: https://kikobeats.com/polyfill-ponyfill-and-prollyfill/#prollyfill

**Comment by just-boris** [comment]
Not sure how many developers are familiar with the term. The same also applies to "ponyfill". At the first time it may look nice and fun (🦄 ), but after seing it 100+ times, I would prefer using "unobtrusive polyfill" to be more explicit and friendly to people non-familiar with this jargon.

I guess formatting it as [Prolyfill](https://kikobeats.com/polyfill-ponyfill-and-prollyfill/#prollyfill) (with a hyperlink) would work, but I do not understand why not to use the official term.

**Comment by karlhorky** [comment]
Ah, you're suggesting to use "speculative polyfills", I must have missed that part. Yeah that seems good too! Actually more explicit 👍

**Comment by just-boris** [comment]
I see two action items here

1. Update the readme, add a warning about current status of the standard: https://github.com/markcellus/cookie-store/pull/142
2. Remove assignments to the `window` object here

https://github.com/markcellus/cookie-store/blob/master/src/index.ts#L301-L305

The second part I would leave to the project maintainers, because it will also require a new major release

**Comment by markcellus** [comment]
@just-boris merged your #142, which addresses your first point (and what I believe to be the reason this thread was opened). 

While your second point above is a good one, we should probably open that in another thread, so we can close this one. Thanks!
