### ISSUE TITLE
Type definitions seems to be a mistake

### ISSUE THREAD

**Issue by SteveYuOWO** [markcellus/cookie-store#145]
Shows typescript error
```
window.cookieStore.set({
  name: 'cookieConsents',
  value: '12345',
  expires,
});
```
Why just only support `set(name: string, value: string)`, not support payload ?
I see master branch is support `set(init: CookieListItem | string, possibleValue?: string)`

**Comment by markcellus** [comment]
Thanks for bringing this up, @SteveYuOWO. The README is reflecting the most recent version of the project. But it hasn't been published to npm yet. Closing this as a duplicate of #132. I will leave an update in that thread shortly.
