### ISSUE TITLE
get method returns undefined when a cookie is not found instead of null

### ISSUE THREAD

**Issue by AnthonyLenglet** [markcellus/cookie-store#156]
under all chromium browsers
```
await cookieStore.get('hello')
```
returns `null`

![image](https://user-images.githubusercontent.com/36004334/157421026-1b8e04ee-d7c7-4459-9587-95af973c1e15.png)

however, in other browsers and in tests, this polyfill returns `undefined`

![image](https://user-images.githubusercontent.com/36004334/157420964-83bbbb14-8e44-4a59-885d-222cabb73f11.png)

this is due to the return value being the first value of an empty array
```
return (await this.getAll(init))[0]
```

**Comment by AnthonyLenglet** [comment]
this was in version 4 !

**Comment by markcellus** [comment]
Thanks. I just verified that [the specification of `get()`](https://wicg.github.io/cookie-store/#CookieStore-get) says it should return `undefined`. But maybe I'm missing something. Where do you see that it should return `null`? I'm wondering if this is perhaps a Chromium bug...

**Comment by markcellus** [comment]
@keithamus @koddsson any thoughts on this one?

**Comment by AnthonyLenglet** [comment]
just checked and you're right that it might actually be a chromium bug instead, it still gives out `null` on both the latest edge and latest chrome

**Comment by keithamus** [comment]
Sounds like Chrome might not be adhering to the spec. Might be worth filing on crbug.com!

**Comment by AnthonyLenglet** [comment]
Moved to a thread on crbug:
https://bugs.chromium.org/p/chromium/issues/detail?id=1355228
